### PR TITLE
Fix missing underscore

### PR DESCRIPTION
**Pull request by MatusGasparik**
See [here](https://github.com/ES-Alexander/pythonic-cv/blob/3a120acfa12492e6bdceb318a0d0f1bcb23d53d8/src/pcv/vidIO.py#L325)

### CODE REVIEW

**Review by ES-Alexander — COMMENTED** [review]
Looks good! Thanks for picking this up :-)

Would you be able to rebase this onto `master`, to avoid the extra merge commit? It helps to keep the history clean :-)

**Comment by MatusGasparik** [comment]
Sorry, this would be my first PR...  ;-)
I pushed to master in my fork of your repo, but of course I forgot to pull in your changes first, so I have an extra merge commit on top of the actual (single-character) fix commit.... Would you mind giving me some hints of how to remedy this?  

Do I need to undo the last commit in my fork? And then start again making sure I first pull your changes first?

**Comment by ES-Alexander** [comment]
> Sorry, this would be my first PR... ;-)

All good - figured I'd make the suggestion and see if you'd done a rebase before or if you wanted some help with it :-)

> I pushed to master in my fork of your repo, but of course I forgot to pull in your changes first

Super common when starting out - not something to worry about :-)

> Do I need to undo the last commit in my fork? And then start again making sure I first pull your changes first?

Normally it's best to make any changes/fixes in a new branch, and keep any branches from the project you've forked clean/use them to track changes in the original project. That makes it easier to restart things if you need to, but also means it's a bit easier for you to start separate branches from a clean branching point rather than basing them off other changes you may not have finalised yet.

Regardless, to fix the current situation you can use an interactive `rebase` to rewrite/modify your history. Assuming you're using git from the command-line,
1. `git pull` the latest changes (since you did the merge in github)
2. then run `git rebase -i HEAD~2` to **i**nteractively **rebase** from 2 commits before your current state(HEAD). That will then bring up a window showing the changes from those commits, e.g.:
    ```
    pick c2be7fe fix missing underscore in OpenCVSource.get()
    pick 1255eb1 vidIO: improve timestamp clarity
    pick 3a120ac README: add Contributors section
    
    # ... a bunch of instructions on what can be done in a rebase
    ```
3. You want to move your commit down to the bottom so it's the most recent one, e.g.
    ```
    pick 1255eb1 vidIO: improve timestamp clarity
    pick 3a120ac README: add Contributors section
    pick c2be7fe fix missing underscore in OpenCVSource.get()
    
    # ...
    ```
    If your rebase is happening in vim (generally the default), navigate with your arrow keys to the line with your commit, then press `dd` (`d`, twice) to cut that line, then move the cursor down to the line with the latest commit, and press `p` to paste (automatically on the next line below). Then to confirm type the command `:wq` (`:` -> 'command', `w` -> 'write', `q` -> quit), and press `Enter`.

4. Once the rebase is complete, you'll need to push the changes back up to your github repo, but in this case because you've changed the history you'll need to "force" the push (`git push --force`). 
    
    As a note, force pushing is generally bad practice once others are using the code, but since this is your own fork and in a pull request it's fine (although as before it's preferable if this kind of thing happens in its own branch)

Once changes have been pushed to the branch your pull request originates from, they should automatically show up here :-)

**Comment by MatusGasparik** [comment]
Wow, thanks for this detailed explanation. I'll do it as soon as I have the
opportunity. It's a little busy atm.

I assumed that in order to be able (at least using the auto mechanism in
github) to create pull requests in upstream repositories, I'd need to
commit to branches that exist in the upstream. So the idea is?:

1) work with new branches within my fork
2) when done, pull newest upstream changes
3a) rebase (or merge, based on the wishes of the maintainer) the changes
from the new branch on top of my fork's master (or other branch that exists
upstream) and create PR

OR?

3b) push the new branch to my fork and create PR for the upstream branch
directly from this new branch (is it possible?)

Note, that I don't want to steal your time, so no worries if you don't want
to waste it on me. I'll figure it out eventually...


ES-Alexander ***@***.***> schrieb am Mi., 17. Nov. 2021,
09:43:

**Review by ES-Alexander — APPROVED** [review]
Looks great, thanks! :-)

I had intended to get back to you on your question, but had a bunch of other stuff come up, and you've seemingly resolved the issue.

For your reference, my normal process is to branch off (in my fork) from the branch I want to modify (usually `master`/`main`, but sometimes some other branch), and then make a PR from my new branch to the original branch in the upstream repo. GitHub doesn't care which branch you PR from or to - you specify that when you're making the PR.

As an extra tidbit, there's a git command called `cherry-pick`, which lets you select specific commits that you want. It's even possible to cherry pick a single commit from someone else's fork of a repo into one of your own. The main point there being git is focused on differences and changes - it operates on pretty much anything you ask it to, so the start and end points for getting or contributing code, or comparisons between code, are generally up to you as a user :-)

**Pull request merged**
